export const offerFormSchema = [
    {
        id: "general",
        title: "01-SİPARİŞ İLE İLGİLİ GENEL BİLGİLER",
        fields: [
            { name: "teklifNo", label: "Teklif Numarası", type: "text", required: true },
            { name: "satisSorumlusu", label: "Satış Sorumlusu", type: "select", options: ["Metin Ünal", "Sinan Gülen", "Ufuk Özünlü"] },
            { name: "siparisCinsi", label: "Sipariş Giren/Satış Destek", type: "select", options: ["Metin Ünal", "Sinan Gülen"] },
            { name: "musteriAdi", label: "Müşteri Adı", type: "text", required: true, placeholder: "Cari Listeden Seçilebilir" },
            { name: "yurtIciDisi", label: "Yurt İçi/Yurt Dışı", type: "radio", options: ["Yurt İçi (Yi)", "Yurt Dışı (YD)"] },
            { name: "musteriTipi", label: "Müşteri Tipi", type: "select", options: ["Bayi", "Kamu", "Özel", "Stok Sipariş"] },
            { name: "siparisAdeti", label: "Sipariş Adeti", type: "number" },
            { name: "onayTarihi", label: "Müşteri Sipariş Onay Tarihi", type: "date" },
            { name: "talepTarihi", label: "Müşteri Talep Tarihi", type: "date" },
            { name: "tipOnayDurumu", label: "Tip Onay Belge Durumu", type: "select", options: ["Var", "Yok"] },
            { name: "tescilUlkesi", label: "Tescil Ülkesi", type: "select", options: ["Türkiye", "Bulgaristan", "Macaristan", "Polonya", "Portekiz", "Romanya", "Sırbistan", "Ukrayna", "Yunanistan", "KKTC", "Türkmenistan", "Azerbaycan", "Gürcistan", "Gana", "Nijerya", "Cezayir", "Katar", "Rusya", "Özbekistan", "Suudi Arabistan", "Liberya", "Umman", "Libya"] },
            { name: "sasiTipi", label: "Şasi Tipi", type: "select", options: ["Yarı Römork Şase", "Muavin Şase (Kamyon Üstü)"] },
            { name: "ustYapiTipi", label: "Üst Yapı Tipi", type: "select", options: ["Havuz Küvet / Kasa", "Jumbo Küvet / Kasa", "Half Pipe", "Köşeli Küvet / Kasa", "Karla Mücadele", "2 Yana Devirme", "3 Yana Devirme", "Akordeon Kasa", "Sac Lambiri Kasa", "Kapaklı Sabit Kasa", "Ahşap Kasa", "Üst Yapı Yok", "Diğer"] },
            { name: "teslimSekli", label: "Teslim Şekli", type: "select", options: ["Komple Teslim", "Müşteri Çekicisi İle Teslim", "Aracı Cekici İle Teslim"] },
            { name: "kamyonMarkasi", label: "Kamyon Markası", type: "select", options: ["FORD", "ISUZU", "MAN", "RENAULT", "SCANIA", "VOLVO", "MercedesBenz", "IVECO", "ASTRA", "HYUNDAI", "MITSUBISHI", "DAF", "BMC", "MACK", "Belirtilmemiş"] },
            { name: "kamyonModeli", label: "Kamyon Modeli", type: "text" },
            { name: "kamyonTahrikSistemi", label: "Kamyon Tahrik Sistemi", type: "select", options: ["4x2", "6x2", "6x4", "8x2", "8x4"] },
            { name: "kamyonKabinTipi", label: "Kamyon Kabin Tipi", type: "select", options: ["Yataklı", "Yataksız"] },
            { name: "kamyonTeslimTarihi", label: "Kamyon Teslim Tarihi", type: "date" },
            { name: "kamyonTalebi", label: "Kamyon Talebi", type: "select", options: ["Var", "Yok"] },
        ]
    },
    {
        id: "kasa",
        title: "02-KASA/KUVET İLE İLGİLİ BİLGİLER",
        fields: [
            { name: "hacim", label: "Hacim", type: "select", options: ["18 m³", "19 m³", "20 m³", "22 m³", "18+2 m³", "19+2 m³", "20+2 m³", "22+2 m³"] },
            { name: "kasaUzunlugu", label: "Kasa Uzunluğu", type: "text" },
            { name: "kasaGenisligi", label: "Kasa Genişliği", type: "text" },
            { name: "kasaYuksekligi", label: "Kasa Yüksekliği", type: "text" },
            { name: "sacKalinliklari", label: "Kuvet Sac Kalınlıkları (Yan - Ön - Taban - Arka)", type: "select", options: ["5 - 4 - 4 - 5 mm", "6 - 4 - 4 - 5 mm", "6 - 5 - 5 - 5 mm", "Diğer"] },
            { name: "damperSacMalzemesi", label: "Damper Kuvet Sacı Malzemesi", type: "select", options: ["Hardox", "MC700", "ST52", "ST37", "CrNi - 304 L", "Domex", "Docol"] },
            { name: "arkaKapakTipi", label: "Arka Kapak Tipi", type: "select", options: ["Mekanik", "Hidrolik"] },
            { name: "siperlik", label: "Siperlik", type: "select", options: ["Var", "Yok"] },
            { name: "emniyetKilitlemesi", label: "Emniyet Kilitlemesi", type: "select", options: ["Var", "Yok"] },
            { name: "brandaTipi", label: "Branda Tipi", type: "select", options: ["Yok", "Branda Hazırlık", "Kancalı (Serme)", "Mekanik Arkaya Açma", "Mekanik Yana Açma", "Otomatik"] },
            { name: "yagTanki", label: "Yağ Tankı", type: "select", options: ["Yok", "Şase Üstü", "Çekici Üstü"] },
            { name: "yagTankiMarkasi", label: "Yağ Tankı Markası", type: "select", options: ["Seka", "HYVA", "Yok", "Diğer"] },
            { name: "silindirMarkasi", label: "Silindir Markası", type: "select", options: ["Üretici Seçimi", "HYVA", "Hidromas"] },
            { name: "silindirTipi", label: "Silindir Tipi", type: "text", placeholder: "Manuel Girilecek" },
            { name: "kunekTipi", label: "Kürek Tipi", type: "select", options: ["Kısa", "Uzun"] },
            { name: "govdeEtekSaci", label: "Gövde Etek Sacı", type: "select", options: ["Var", "Yok"] },
        ]
    },
    {
        id: "sasi",
        title: "03-ŞASİ/YÜRÜYEN İLE İLGİLİ BİLGİLER",
        fields: [
            { name: "dingilMesafesi", label: "Dingil Mesafesi (Wb)", type: "select", options: ["3600", "3800", "3815", "3900", "4350", "4500", "4800", "5100", "5150"] },
            { name: "dingillerArasiMesafe", label: "Dingiller Arası Mesafe", type: "select", options: ["Yok", "1350"] },
            { name: "besinciTekerYuksekligi", label: "5. Tekerlek Yüksekliği", type: "text", placeholder: "Manuel Girilecek" },
            { name: "disUzunluk", label: "Dış Uzunluk", type: "text", placeholder: "Manuel Girilecek" },
            { name: "aracGenisligi", label: "Araç Genişliği", type: "text", placeholder: "Manuel Girilecek" },
            { name: "aracYuksekligi", label: "Araç Yüksekliği", type: "text", placeholder: "Manuel Girilecek" },
            { name: "dingilYuku", label: "Dingil Yükü", type: "select", options: ["18.000 kg", "20.000 kg", "24.000 kg", "27.000 kg"] },
            { name: "kingpinKapasitesi", label: "Kingpin Kapasitesi", type: "select", options: ["12.000 kg", "15.000 kg", "16.500 kg", "18.000 kg"] },
            { name: "mekanikAyak", label: "Mekanik Ayak", type: "select", options: ["JOST", "OMS", "SAF"] },
            { name: "elektrikSistemi", label: "Elektrik Sistemi", type: "select", options: ["Müşteri Talebi", "Standart"] },
            { name: "tampon", label: "Tampon", type: "select", options: ["Sabit Tampon", "Katlanır Tampon"] },
            { name: "dingilMarkasi", label: "Dingil Markası", type: "select", options: ["BPW Disk", "BPW Kampana", "TRAX Disk", "TRAX Kampana"] },
            { name: "dingilSayisi", label: "Dingil Sayısı", type: "select", options: ["2 ADT", "3 ADT"] },
            { name: "dingilKaldirma", label: "Dingil Kaldırma", type: "select", options: ["1. Dingil Kaldırma", "1 ve 2. Dingil Kaldırma", "Yok"] },
            { name: "dingilKaldirmaKumandasi", label: "Dingil Kaldırma Kumandası", type: "select", options: ["Otomatik+Kabinden Sürüş Yrd.", "Yok"] },
            { name: "frenSistemi", label: "Fren Sistemi", type: "select", options: ["EBS 2S/2M"] },
            { name: "frenSistemiMarkasi", label: "Fren Sistemi Markası", type: "select", options: ["Haldex", "Knorr", "Wabco", "Yok"] },
            { name: "guvenlikFrenFonksiyonu", label: "Güvenlik Fren Fonksiyonu", type: "select", options: ["Standart"] },
            { name: "lastikMarkasi", label: "Lastik Markası", type: "select", options: ["Bridgestone", "Continantel", "Goodyear", "Hankook", "Lassa", "Michelin", "Özünlü Seçimi", "Pirelli"] },
            { name: "lastikEbadi", label: "Lastik Ebadı", type: "select", options: ["385/65 R22.5"] },
            { name: "toplamLastikJantAdeti", label: "Toplam Lastik-Jant Adeti", type: "select", options: ["4 ADT", "5 ADT", "6 ADT", "7 ADT"] },
            { name: "jantMarkasi", label: "Jant Markası", type: "select", options: ["Özünlü Seçim"] },
            { name: "jantTipi", label: "Jant Tipi", type: "select", options: ["Çelik", "Çelik Ofsetli", "Standart"] },
            { name: "stepneTasiyiciTipi", label: "Stepne Taşıyıcı Tipi", type: "select", options: ["Damper Üstü", "Şase Üstü", "Yok"] },
            { name: "camurlukTipi", label: "Çamurluk Tipi", type: "select", options: ["Sac Çamurluk", "Plastik Çamurluk"] },
            { name: "camurlukMarkasi", label: "Çamurluk Markası", type: "select", options: ["Nevpa", "Üretici Seçimi", "Yok"] },
        ]
    },
    {
        id: "diger",
        title: "04-DİĞER ÖZELLİKLER",
        fields: [
            { name: "yanginDolabi", label: "Yangın Dolabı", type: "select", options: ["1 Adet Yangın Dolabı (Tüpsüz)", "2 Adet Yangın Dolabı (Tüpsüz)", "Yok"] },
            { name: "dolapTipi", label: "Dolap Tipi", type: "select", options: ["1 AD. Plastik Takım Dolabı 600", "Yok"] },
            { name: "suDeposu", label: "Su Deposu", type: "select", options: ["Var", "Yok"] },
            { name: "isaretveLevhalar", label: "İşaret ve Levhalar", type: "select", options: ["Standart"] },
            { name: "merdiven", label: "Merdiven", type: "select", options: ["Var", "Yok"] },
            { name: "orjinalPto", label: "Orjinal Pto", type: "select", options: ["Evet", "Hayır"] },
            { name: "hidrolikPompa", label: "Hidrolik Pompa", type: "select", options: ["Çift Kademe 82l/dk", "Çift Kademe 61l/dk", "Tek Kademe 61l/dk", "Tek Kademe 82l/dk"] },
            { name: "dengeKolu", label: "Denge Kolu", type: "select", options: ["Var", "Yok"] },
            { name: "cekiSeti", label: "Çeki Seti", type: "select", options: ["Var", "Yok"] },
            { name: "sasiRengi", label: "Şasi Rengi", type: "select", options: ["RAL XXXX Füme", "RAL XXXX Siyah"] },
            { name: "damperKuvetRengi", label: "Damper Kuvet Rengi", type: "select", options: ["RAL XXXX Beyaz", "RAL XXXX Füme", "RAL XXXX İren Sarısı", "RAL XXXX Kavun Sarısı", "RAL XXXX Lacivert", "RAL XXXX Turuncu"] },
            { name: "brandaRengi", label: "Branda Rengi", type: "select", options: ["RAL XXXX Beyaz", "RAL XXXX Füme", "RAL XXXX İren Sarısı", "RAL XXXX Kavun Sarısı", "RAL XXXX Lacivert", "RAL XXXX Turuncu"] },
            { name: "logo", label: "Logo", type: "select", options: ["Var", "Yok"] },
            { name: "uyariEtiketDili", label: "Uyarı Etiket Dili", type: "select", options: ["İngilizce", "Türkçe"] },

        ]
    }
];
